// A TOY elliptic curve over a small prime field, for visualization only.
//
//   y^2 = x^3 + a*x + b   (mod p)
//
// We use the same shape as secp256k1 (a=0, b=7) but a tiny prime so every
// point fits on a grid and the group is small enough to brute-force by hand.
// THIS IS NOT SECURE. Real curves use ~256-bit primes (~2^256 points). The
// whole point of the small field is to *feel* the one-way property: computing
// k*G is easy, but recovering k from k*G (the discrete-log problem) means
// trying every k — trivial here, astronomically hard on a real curve.

export interface ToyCurve {
  a: bigint
  b: bigint
  p: bigint
}

// Point at infinity is represented as null.
export type Point = { x: bigint; y: bigint } | null

// Default demo curve: y^2 = x^3 + 7 mod 97. It has 78 affine points, so the
// group order is 79 (prime) — meaning every non-identity point generates the
// whole group. (1, 28) is verified on-curve with order 79.
export const DEFAULT_CURVE: ToyCurve = { a: 0n, b: 7n, p: 97n }
export const DEFAULT_GENERATOR: Point = { x: 1n, y: 28n }

function mod(n: bigint, p: bigint): bigint {
  return ((n % p) + p) % p
}

/** Modular inverse via extended Euclid (p is prime here). */
function inv(n: bigint, p: bigint): bigint {
  let [old_r, r] = [mod(n, p), p]
  let [old_s, s] = [1n, 0n]
  while (r !== 0n) {
    const q = old_r / r
    ;[old_r, r] = [r, old_r - q * r]
    ;[old_s, s] = [s, old_s - q * s]
  }
  return mod(old_s, p)
}

/** Every affine point on the curve (excluding the point at infinity). */
export function allPoints(curve: ToyCurve): Point[] {
  const { a, b, p } = curve
  const pts: Point[] = []
  for (let x = 0n; x < p; x++) {
    const rhs = mod(x * x * x + a * x + b, p)
    for (let y = 0n; y < p; y++) {
      if (mod(y * y, p) === rhs) pts.push({ x, y })
    }
  }
  return pts
}

/** Point addition with the chord-and-tangent rule. */
export function add(P: Point, Q: Point, curve: ToyCurve): Point {
  if (P === null) return Q
  if (Q === null) return P
  const { a, p } = curve
  if (P.x === Q.x && mod(P.y + Q.y, p) === 0n) return null // P + (-P) = O

  let lambda: bigint
  if (P.x === Q.x && P.y === Q.y) {
    // tangent (doubling)
    lambda = mod((3n * P.x * P.x + a) * inv(2n * P.y, p), p)
  } else {
    // chord
    lambda = mod((Q.y - P.y) * inv(Q.x - P.x, p), p)
  }
  const x = mod(lambda * lambda - P.x - Q.x, p)
  const y = mod(lambda * (P.x - x) - P.y, p)
  return { x, y }
}

/** Scalar multiplication k*P via double-and-add. */
export function scalarMul(k: bigint, P: Point, curve: ToyCurve): Point {
  let result: Point = null
  let addend: Point = P
  let n = k
  while (n > 0n) {
    if (n & 1n) result = add(result, addend, curve)
    addend = add(addend, addend, curve)
    n >>= 1n
  }
  return result
}

/** The cyclic subgroup generated by G: [G, 2G, 3G, ... , O]. */
export function subgroup(G: Point, curve: ToyCurve): Point[] {
  const out: Point[] = []
  let cur: Point = G
  for (let i = 0; i < 1000; i++) {
    out.push(cur)
    cur = add(cur, G, curve)
    if (cur === null) {
      out.push(null) // identity, closes the cycle
      break
    }
    if (cur && G && cur.x === G.x && cur.y === G.y) break
  }
  return out
}

/** Order of G = number of points in its subgroup (including O). */
export function order(G: Point, curve: ToyCurve): number {
  return subgroup(G, curve).length
}
